[versions]
androidx-activity = "1.7.2"
androidx-lifecycle = "2.6.1"
androidx-compose = "1.5.0"
androidx-compose-compiler = "1.5.0"
coroutines = "1.7.3"
jetbrains-compose = "1.5.0-beta01"
jetbrains-compose-compiler = "1.5.0"
ktlint = "0.50.0"
okio = "3.5.0"
roborazzi = "1.3.0"

[plugins]
binaryCompatibility = "org.jetbrains.kotlinx.binary-compatibility-validator:0.13.2"
dokka = "org.jetbrains.dokka:1.8.20"
spotless = "com.diffplug.spotless:6.20.0"

[libraries]
gradlePlugin-android = "com.android.tools.build:gradle:8.1.0"
gradlePlugin-atomicFu = "org.jetbrains.kotlinx:atomicfu-gradle-plugin:0.21.0"
gradlePlugin-jetbrainsCompose = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "jetbrains-compose" }
gradlePlugin-kotlin = "org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.0"
gradlePlugin-mavenPublish = "com.vanniktech:gradle-maven-publish-plugin:0.25.3"
gradlePlugin-paparazzi = "app.cash.paparazzi:paparazzi-gradle-plugin:1.3.1"
gradlePlugin-roborazzi = { module = "io.github.takahirom.roborazzi:roborazzi-gradle-plugin", version.ref = "roborazzi" }

accompanist-drawablepainter = "com.google.accompanist:accompanist-drawablepainter:0.30.1"

androidx-activity = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-appcompat-resources = "androidx.appcompat:appcompat-resources:1.6.1"
androidx-annotation = "androidx.annotation:annotation:1.6.0"
androidx-benchmark-macro = "androidx.benchmark:benchmark-macro-junit4:1.2.0-beta03"
androidx-constraintlayout = "androidx.constraintlayout:constraintlayout:2.1.4"
androidx-core = "androidx.core:core-ktx:1.10.1"
androidx-exifinterface = "androidx.exifinterface:exifinterface:1.3.6"
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-profileinstaller = "androidx.profileinstaller:profileinstaller:1.3.1"
androidx-recyclerview = "androidx.recyclerview:recyclerview:1.3.1"
androidx-test-core = "androidx.test:core-ktx:1.5.0"
androidx-test-espresso = "androidx.test.espresso:espresso-core:3.5.1"
androidx-test-junit = "androidx.test.ext:junit-ktx:1.1.5"
androidx-test-rules = "androidx.test:rules:1.5.0"
androidx-test-runner = "androidx.test:runner:1.5.2"
androidx-test-uiautomator = "androidx.test.uiautomator:uiautomator:2.2.0"
androidx-vectordrawable-animated = "androidx.vectordrawable:vectordrawable-animated:1.1.0"

androidx-compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "androidx-compose" }
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "androidx-compose" }
androidx-compose-ui-test = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "androidx-compose" }

jetbrains-compose-compiler = { module = "org.jetbrains.compose.compiler:compiler", version.ref = "jetbrains-compose-compiler" }
jetbrains-compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "jetbrains-compose" }
jetbrains-compose-material = { module = "org.jetbrains.compose.material:material", version.ref = "jetbrains-compose" }

coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

junit = "junit:junit:4.13.2"

kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test-junit" }

kotlinx-immutable-collections = "org.jetbrains.kotlinx:kotlinx-collections-immutable:0.3.5"

ktlint = { module = "com.pinterest.ktlint:ktlint-core", version.ref = "ktlint" }

ktor-core = "io.ktor:ktor-client-core:2.3.2"

material = "com.google.android.material:material:1.9.0"

okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
okio-fakefilesystem = { module = "com.squareup.okio:okio-fakefilesystem", version.ref = "okio" }

robolectric = "org.robolectric:robolectric:4.10.3"

roborazzi-core = { module = "io.github.takahirom.roborazzi:roborazzi", version.ref = "roborazzi" }
roborazzi-compose = { module = "io.github.takahirom.roborazzi:roborazzi-compose", version.ref = "roborazzi" }
roborazzi-junit = { module = "io.github.takahirom.roborazzi:roborazzi-junit-rule", version.ref = "roborazzi" }

skiko = "org.jetbrains.skiko:skiko:0.7.67"

svg = "com.caverock:androidsvg-aar:1.4"

[bundles]
test-android = [
    "androidx-test-core",
    "androidx-test-junit",
    "androidx-test-rules",
    "androidx-test-runner",
    "coroutines-test",
    "junit",
    "kotlin-test",
]
test-common = [
    "coroutines-test",
    "kotlin-test",
    "okio-fakefilesystem",
]
test-jvm = [
    "androidx-test-core",
    "androidx-test-junit",
    "androidx-test-rules",
    "androidx-test-runner",
    "coroutines-test",
    "junit",
    "kotlin-test",
    "okio-fakefilesystem",
    "robolectric",
]
